### PR TITLE
Delete math.py

### PR DESCRIPTION
**Pull request by WeebTime**

### CODE REVIEW

**Comment by JayPatel1314** [comment]
@ShinchanNohara1 @uday_gondaliya Wtf

**Comment by JayPatel1314** [comment]
@JayPatel1314 Kyaaab👀

**Comment by ShinchanNohara1** [comment]
no need of this module

**Comment by WeebTime** [comment]
ara ara sayonara

**Comment by JayPatel1314** [comment]
@WeebTime Chala jaaa

**Pull request closed without merging**
